### PR TITLE
replacing `quit()` with `sys.exit()`

### PR DESCRIPTION
**Pull request by zocker-160**
`quit()` should not be used in production code because it is only meant to be used in the interactive mode of the interpreter

### CODE REVIEW

**Comment by hwittenborn** [comment]
There's been a lot of changes after the `python-apt` port, so there's probably gonna be a lot more uses of `exit()` scattered throughout.

If you'd like to take that on still though I'm fine with that, otherwise I'll look into doing it in the future.

**Comment by hwittenborn** [comment]
Is there any interest on your part on finishing this, or do you think it would be more appropriate to close the PR?

All up to you :)

**Comment by zocker-160** [comment]
I will finish this, but I sadly did not have the time to do it this week.

**Comment by hwittenborn** [comment]
Should I still keep this open? It's been a bit, but I just wanted to check on the current status with you.

**Comment by zocker-160** [comment]
@hwittenborn I working on it right now, I will rebase everything and update the PR

**Comment by zocker-160** [comment]
done, should be ready to merge

**Comment by zocker-160** [comment]
closing, since there does not seem to be any interest in this whatsoever

**Pull request closed without merging**
