### PR TITLE
Add make dependency to PKGBUILD

### PR DESCRIPTION
**Pull request by cat-master21**
Requires make which is not installed and by default make is not installed on Ubuntu 20.04:
failed-build
 So make needs to be added to makedepends.

### CODE REVIEW

**Review by hwittenborn — APPROVED** [review]
Lgtm, I'll get this merged later :)

**Comment by cat-master21** [comment]
@hwittenborn can't this be merged yet? It's been over a week since approval.

**Comment by hwittenborn** [comment]
That's my bad - I just wasn't really focused on Tap rn, so I wasn't gonna be prepared to fix anything if the CI failed during deployment.

I'll go ahead and get it merged today though.

**Review by hwittenborn — APPROVED** [review]
Let's get it merged :D

**Pull request merged**
