### PR TITLE
Create tap.fish

### PR DESCRIPTION
**Pull request by ivanottantuno**
fish completions for tap derived from the apt ones

### CODE REVIEW

**Comment by hwittenborn** [comment]
Would there be any way for the completions to support completing packages names for the `install`, `remove` and `list` commands? Currently a file at `/var/cache/tap/pkglist` is used to complete package names for Bash completions (they were added in a pretty recent commit), but I wasn't sure if your fish ones were as well.

**Review by ivanottantuno — COMMENTED** [review]
Now the install search and list subcommands are using /var/cache/tap/pkglist to complete package names.
Only the remove subcommands use the internal fish function "__fish_print_packages" with the flag --installed, so it does the completion only with the installed packages.

**Comment by ivanottantuno** [comment]
I think this will work
https://github.com/hwittenborn/tap/pull/29/commits/db78d0037bdd0e89f83ec08496e4c62345c9ea6c

Il giorno lun 20 dic 2021 alle ore 00:33 Hunter Wittenborn <
***@***.***> ha scritto:

**Comment by hwittenborn** [comment]
Sorry for the delay on my end; I'll try to test this locally soon and get it merged if it all checks out.

**Comment by hwittenborn** [comment]
I'm archiving this repository, so your PR won't get merged sadly. I just haven't had time to focus on Tap the last few months, and there's no current plans on that changing much, if at all.

**Pull request closed without merging**
